"use client";

import { useState } from "react";

type Status = "Normal" | "Needs attention" | "Completed" | "Upcoming" | "Overdue" | "Pending";
type Feeding = [string, string, string, string, Status];
type MaintenanceTask = [string, string, string, string, Status];

const ponds = [
  { id: "P-01", name: "Lagoon Alpha", species: "Tilapia", fish: "12,480", temp: "28.4", ph: "7.2", oxygen: "6.8", feed: "Complete", status: "Normal" as Status },
  { id: "P-02", name: "Lagoon Beta", species: "Vannamei Shrimp", fish: "18,200", temp: "29.1", ph: "7.8", oxygen: "5.9", feed: "Due in 24 min", status: "Normal" as Status },
  { id: "P-03", name: "Nursery East", species: "Catfish", fish: "8,640", temp: "31.6", ph: "6.4", oxygen: "4.2", feed: "Overdue", status: "Needs attention" as Status },
];
const feedings: Feeding[] = [
  ["06:30", "Lagoon Alpha", "Floating pellets", "18.5 kg", "Completed" as Status],
  ["09:00", "Lagoon Beta", "Shrimp crumble", "12.0 kg", "Upcoming" as Status],
  ["16:30", "Nursery East", "Sinking pellets", "8.4 kg", "Overdue" as Status],
];
const tasks: MaintenanceTask[] = [
  ["◌", "Water quality check", "Lagoon Alpha", "Today, 08:40", "Completed" as Status],
  ["≋", "Clean mechanical filter", "Lagoon Beta", "Today, 07:15", "Completed" as Status],
  ["✚", "Check fish health", "Nursery East", "Due today", "Pending" as Status],
];

function Badge({ status }: { status: Status }) {
  const tone = status === "Normal" || status === "Completed" ? "bg-[#e5f7f0] text-[#18745b]" : status === "Needs attention" || status === "Upcoming" || status === "Pending" ? "bg-[#fff3d8] text-[#a76509]" : "bg-[#ffe5e4] text-[#bd443d]";
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${tone}`}><i className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

function Metric({ title, value, unit, icon, tone = "blue" }: { title: string; value: string; unit: string; icon: string; tone?: string }) {
  const colors = tone === "teal" ? "bg-[#e4f8f2] text-[#16856d]" : tone === "amber" ? "bg-[#fff3dd] text-[#b87614]" : "bg-[#e6f3ff] text-[#1975bb]";
  return <div className="rounded-2xl border border-[#e1eaf0] bg-white p-4 shadow-[0_4px_18px_rgba(33,76,104,0.04)]"><div className="flex justify-between"><p className="text-xs font-medium text-[#8293a0]">{title}</p><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${colors}`}>{icon}</span></div><div className="mt-4 flex items-baseline gap-1"><b className="text-2xl tracking-[-0.04em] text-[#1e3545]">{value}</b><span className="text-xs text-[#8a9aa5]">{unit}</span></div></div>;
}

export default function Home() {
  const [active, setActive] = useState("Overview");
  const [filter, setFilter] = useState("All ponds");
  const visiblePonds = ponds.filter((pond) => filter === "All ponds" || pond.status === filter.replace(" only", ""));
  const nav = ["Overview", "Pond monitoring", "Feeding schedule", "Maintenance", "Fish growth"];

  return (
    <main className="min-h-screen bg-[#f5f9fb] text-[#1e3545]"><div className="flex min-h-screen flex-col lg:flex-row">
      <aside className="flex w-full shrink-0 flex-col border-b border-[#dfeaf0] bg-white px-5 py-5 lg:sticky lg:top-0 lg:h-screen lg:w-[248px] lg:border-b-0 lg:border-r lg:px-4 lg:py-6">
        <div className="flex items-center gap-3 px-2"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1289a5] text-xl text-white">◒</span><div><b className="text-sm text-[#183b50]">Aqua<span className="text-[#15967d]">keep</span></b><p className="text-[10px] uppercase tracking-[0.15em] text-[#91a1aa]">Farm operations</p></div></div>
        <p className="mt-8 hidden text-[10px] font-bold uppercase tracking-[0.17em] text-[#9aabb4] lg:block">Workspace</p>
        <nav className="mt-3 hidden space-y-1 lg:block" aria-label="Dashboard navigation">{nav.map((item, index) => <button key={item} onClick={() => setActive(item)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-medium transition-colors ${active === item ? "bg-[#e7f6f8] text-[#108198]" : "text-[#71838d] hover:bg-[#f3f8fa]"}`}><span className="w-5 text-center">{["⌂", "◉", "◒", "⚙", "↗"][index]}</span>{item}{item === "Pond monitoring" && <small className="ml-auto rounded-full bg-[#d7eff4] px-2 py-0.5">3</small>}</button>)}</nav>
        <div className="mt-auto hidden rounded-2xl bg-[#eef9fa] p-4 lg:block"><p className="text-xs font-bold text-[#267488]">Farm health</p><div className="mt-3 flex justify-between"><b className="text-2xl text-[#126a7b]">94%</b><small className="self-end text-[#3b9a8b]">+4.2% this week</small></div><div className="mt-3 h-1.5 rounded-full bg-[#d1edf0]"><div className="h-full w-[94%] rounded-full bg-[#2fb19a]" /></div></div>
        <div className="mt-6 flex items-center gap-3 border-t border-[#edf1f3] pt-5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#d8eaf2] text-xs font-bold text-[#27728e]">MR</span><div><b className="text-xs text-[#334e5c]">M Rizki Ruswan</b><p className="text-[10px] text-[#91a1aa]">Farm manager</p></div><span className="ml-auto">•••</span></div>
      </aside>

      <div className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-[#e1ebf0] bg-white px-5 py-5 sm:px-8 lg:px-10"><div><p className="text-xs text-[#92a3ac]">Monday, 24 June 2024</p><h1 className="mt-1 text-xl font-bold text-[#203d4c] sm:text-2xl">Good morning, M Rizki Ruswan <span aria-hidden="true">👋</span></h1></div><div className="flex gap-2"><button className="relative flex h-10 w-10 items-center justify-center rounded-xl border border-[#e0ebef] text-lg text-[#617984] hover:bg-[#effafa]" aria-label="Notifications">♧<i className="absolute right-2 top-1.5 h-1.5 w-1.5 rounded-full bg-[#eb7668]" /></button><button className="hidden rounded-xl border border-[#dce9ed] px-3 py-2 text-xs font-semibold text-[#54707b] sm:block">Last 7 days⌄</button></div></header>
        <div className="mx-auto max-w-[1440px] space-y-7 px-5 py-6 sm:px-8 lg:px-10 lg:py-8">
          <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#15927e]">Today&apos;s overview</p><h2 className="mt-2 text-2xl font-bold text-[#203d4c]">Farm at a glance</h2></div><button className="self-start rounded-xl bg-[#1289a5] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#0e718a] sm:self-auto">＋ Log activity</button></section>
          <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Active ponds" value="03" unit="of 04 total" icon="◉" /><Metric title="Fish in cultivation" value="39,320" unit="fish" icon="♧" tone="teal" /><Metric title="Water temperature" value="28.9" unit="°C avg." icon="♨" tone="amber" /><Metric title="Water condition" value="Good" unit="All ponds" icon="✓" tone="teal" /></section>
          <section className="grid gap-6 xl:grid-cols-[1.55fr_1fr]"><div className="rounded-2xl border border-[#deeaef] bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-bold text-[#294b5b]">Pond monitoring</h2><Badge status="Normal" /></div><p className="mt-1 text-xs text-[#94a3ab]">Live readings from your aquaculture ponds</p></div><select value={filter} onChange={(event) => setFilter(event.target.value)} className="rounded-lg border border-[#dce9ee] bg-white px-3 py-2 text-xs text-[#607783]"><option>All ponds</option><option>Normal only</option><option>Needs attention</option></select></div><div className="mt-5 grid gap-3">{visiblePonds.map((pond) => <article key={pond.id} className="rounded-xl border border-[#e4edf1] p-4 transition hover:border-[#9ed2d6] hover:shadow-md"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#e5f6f7] text-[#198a97]">◉</span><div><h3 className="text-sm font-bold text-[#345363]">{pond.name} <small className="text-[#9aabb3]">{pond.id}</small></h3><p className="text-[11px] text-[#8497a1]">{pond.species} · {pond.fish} fish</p></div></div><Badge status={pond.status} /></div><div className="mt-4 grid grid-cols-3 gap-2 border-t border-[#edf2f4] pt-3 text-xs"><div><p className="text-[#98a7ae]">Temp.</p><b>{pond.temp}°C</b></div><div><p className="text-[#98a7ae]">pH level</p><b>{pond.ph}</b></div><div><p className="text-[#98a7ae]">Oxygen</p><b>{pond.oxygen} mg/L</b></div></div><div className="mt-3 flex justify-between text-[11px]"><span className="text-[#93a2a9]">Feeding: <b className={pond.feed === "Overdue" ? "text-[#c7544e]" : "text-[#4a727d]"}>{pond.feed}</b></span><button className="font-bold text-[#17859a]">View details →</button></div></article>)}</div></div>
            <div className="rounded-2xl bg-[#0f758b] p-5 text-white shadow-lg sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a9e4e0]">Attention needed</p><h2 className="mt-2 text-lg font-bold">Pond conditions</h2><div className="mt-6 space-y-3"><div className="rounded-xl border border-white/10 bg-white/10 p-3.5"><b className="text-xs">⚠ Low oxygen in Nursery East</b><p className="mt-1 text-[11px] leading-5 text-[#c5e5e7]">Oxygen is at 4.2 mg/L. Recommended minimum is 5.0 mg/L.</p><button className="mt-2 text-[11px] font-bold text-[#9ee6d4]">Open pond details →</button></div><div className="rounded-xl border border-white/10 bg-white/10 p-3.5"><b className="text-xs">◷ Feeding task is overdue</b><p className="mt-1 text-[11px] leading-5 text-[#c5e5e7]">Nursery East missed the 09:30 feeding schedule.</p><button className="mt-2 text-[11px] font-bold text-[#9ee6d4]">Review schedule →</button></div></div><p className="mt-5 border-t border-white/15 pt-4 text-center text-[11px] text-[#b6dfe0]">2 alerts require your attention</p></div></section>
          <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><div className="rounded-2xl border border-[#deeaef] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#294b5b]">Today&apos;s feeding schedule</h2><p className="mt-1 text-xs text-[#94a3ab]">3 scheduled activities</p></div><button className="text-xs font-bold text-[#16879b]">Manage schedule →</button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[580px] text-left text-xs"><thead className="border-b border-[#edf2f4] text-[10px] uppercase text-[#99a8af]"><tr>{["Time", "Pond", "Feed type", "Amount", "Status"].map((head) => <th key={head} className="pb-3">{head}</th>)}</tr></thead><tbody>{feedings.map((row) => <tr key={row[0]} className="border-b border-[#f0f4f5] last:border-0"><td className="py-4 font-bold">{row[0]}</td><td className="py-4 text-[#627985]">{row[1]}</td><td className="py-4 text-[#8798a0]">{row[2]}</td><td className="py-4 text-[#627985]">{row[3]}</td><td className="py-4 text-right"><Badge status={row[4]} /></td></tr>)}</tbody></table></div></div>
            <div className="rounded-2xl border border-[#deeaef] bg-white p-5 shadow-sm sm:p-6"><h2 className="font-bold text-[#294b5b]">Fish growth</h2><p className="mt-1 text-xs text-[#94a3ab]">Average progress by species</p><div className="mt-5 space-y-5">{[["Tilapia", "72%", "w-[72%]", "284g · 21.4cm"], ["Vannamei shrimp", "58%", "w-[58%]", "18.2g · 12.6cm"]].map(([name, percent, width, detail]) => <div key={name}><div className="flex justify-between text-xs"><b>{name}</b><b className="text-[#17917c]">{percent}</b></div><div className="mt-2 h-2 rounded-full bg-[#e8f0f2]"><div className={`h-full rounded-full bg-[#2cb49a] ${width}`} /></div><p className="mt-1.5 text-[10px] text-[#93a3aa]">Avg. {detail} · measured recently</p></div>)}</div><button className="mt-6 w-full rounded-xl border border-[#dcebef] py-2.5 text-xs font-bold text-[#17869a]">View growth report</button></div></section>
          <section className="grid gap-6 xl:grid-cols-[1fr_0.72fr]"><div className="rounded-2xl border border-[#deeaef] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#294b5b]">Recent maintenance</h2><p className="mt-1 text-xs text-[#94a3ab]">Latest farm activities and records</p></div><button className="text-xs font-bold text-[#16879b]">View all →</button></div><div className="mt-4 grid gap-1">{tasks.map(([icon, title, pond, date, status]) => <div key={title} className="flex items-center gap-3 rounded-xl px-2 py-3 hover:bg-[#f5fafb]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e7f6f5] text-[#198d84]">{icon}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs text-[#496570]">{title}</b><p className="mt-1 text-[10px] text-[#95a4aa]">{pond} · {date}</p></div><Badge status={status} /></div>)}</div></div><div className="rounded-2xl border border-[#d9ebee] bg-gradient-to-br from-[#e9faf7] to-[#e9f6fc] p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#279183]">Quick action</p><h2 className="mt-2 text-lg font-bold leading-7 text-[#235360]">Keep daily records up to date</h2><p className="mt-2 text-xs leading-5 text-[#6f8990]">Log mortality, water changes, or health checks in under a minute.</p><button className="mt-5 rounded-xl bg-[#168d89] px-4 py-2.5 text-xs font-bold text-white">＋ Add maintenance record</button></div></section>
        </div></div>
    </div></main>
  );
}
